// Generated by eBay Common SDK Platform
package com.ebay.services.merchandising.client;

import com.ebay.services.merchandising.GetMostWatchedItemsRequest;
import com.ebay.services.merchandising.MerchandisingServiceItemResponse;
import org.ebay.msif.core.ServiceClientException;

public interface MerchandisingService {

    public MerchandisingServiceItemResponse getMostWatchedItems(GetMostWatchedItemsRequest request) throws ServiceClientException;
    

}
