// Generated by eBay Common SDK Platform
package com.ebay.services.merchandising.client;

import org.ebay.msif.core.ServiceCallback;
import org.ebay.msif.core.ServiceInvoker;
import org.ebay.msif.core.ServiceClientException;
import org.ebay.msif.core.ServiceInvokerFactory;

import android.content.Context;

import com.ebay.services.merchandising.GetMostWatchedItemsRequest;
import com.ebay.services.merchandising.MerchandisingServiceItemResponse;

public class MerchandisingServiceClient {

    ServiceInvoker m_invoker;
    Context m_appContext;
    
    // default constructor
	public MerchandisingServiceClient(Context appContext) {
		m_appContext = appContext;
	}
	
    public ServiceInvoker getInvoker() throws ServiceClientException {
        if (m_invoker == null) {
			m_invoker = ServiceInvokerFactory.createInstance("MerchandisingService", MerchandisingService.class, new MerchandisingServiceAccessPolicy(), m_appContext);
        }
        return m_invoker;
    }

    public void getMostWatchedItems(GetMostWatchedItemsRequest req, ServiceCallback<MerchandisingServiceItemResponse> callback) throws ServiceClientException {
        getInvoker().invoke("getMostWatchedItems", req, callback);
    }
	

}
