// Generated by eBay Common SDK Platform
package com.ebay.services.merchandising;

import com.ebay.jxb.annotation.*;
/**
 * 
 * Basic type for specifying monetary amounts. A double value (e.g.,1.00 or 1.0) is
 * meaningful as a monetary amount when accompanied by a specification of the
 * currency, in which case the value specifies the amount in that currency. An
 * AmountType expresses both the value (a double) and the currency. Details such as
 * prices, fees, costs,and payments are specified as amount types.
 * 
 */
@Root(name = "Amount")
@Namespace(namespaceURI="http://www.ebay.com/marketplace/services", prefix="")
public class Amount   {


	@Text
	private double value;
	

	@Attribute(name="currencyId")
	private String currencyId;
	
    
	public double getValue() {
	    return this.value;
	}
	
	public void setValue(double value) {
	    this.value = value;
	}
	
	public String getCurrencyId() {
	    return this.currencyId;
	}
	
	public void setCurrencyId(String currencyId) {
	    this.currencyId = currencyId;
	}
	
}