// Generated by eBay Common SDK Platform
package com.ebay.services.merchandising;

import com.ebay.jxb.annotation.*;
import com.ebay.types.common.soa.BaseServiceResponse;
/**
 * 
 * Base response container for all service operations in the Merchandising Service.
 * 
 */
@Root(name = "BaseMerchandisingServiceResponse")
@Namespace(namespaceURI="http://www.ebay.com/marketplace/services", prefix="")
public abstract class BaseMerchandisingServiceResponse extends BaseServiceResponse  {

    
}