// Generated by eBay Common SDK Platform
package com.ebay.services.merchandising;

import com.ebay.jxb.annotation.*;
import com.ebay.types.common.soa.BaseServiceRequest;
import com.ebay.types.common.soa.Affiliate;
/**
 * 
 * This is the base class for request container for all operations in the
 * Merchandising Service.
 * 
 */
@Root(name = "BaseMerchandisingServiceRequest")
@Namespace(namespaceURI="http://www.ebay.com/marketplace/services", prefix="")
public abstract class BaseMerchandisingServiceRequest extends BaseServiceRequest  {


	@Element(name="maxResults")
	private Integer maxResults;
	

	@Element(name="affiliate")
	private Affiliate affiliate;
	
    
	/**
     * 
     * Specifies the maximum number of entries to return in a single call.
     * If the number of entries that can be returned is less than the value
     * you specify, the lower number is returned. Values less than 1 or
     * greater than 50 will be ignored.
     * 
	 */
	public Integer getMaxResults() {
	    return this.maxResults;
	}
	
	public void setMaxResults(Integer maxResults) {
	    this.maxResults = maxResults;
	}
	
	/**
     * 
     * Container for affiliate details. eBay uses the specified affiliate
     * details to build a View Item URL and Product URL string in the
     * response that includes your affiliate tracking information in the
     * correct format. When a user clicks through these URLs to eBay and
     * performs certain tasks, you may get an affiliate commission.
     * <br><br> 
     * See the <a href="https://www.ebaypartnernetwork.com/"
     * target="_blank">eBay Partner Network</a> for information
     * about commissions.
     * 
	 */
	public Affiliate getAffiliate() {
	    return this.affiliate;
	}
	
	public void setAffiliate(Affiliate affiliate) {
	    this.affiliate = affiliate;
	}
	
}