// Generated by eBay Common SDK Platform
package com.ebay.services.merchandising;

import com.ebay.jxb.annotation.*;
/**
 * 
 * Retrieves data for items with the highest watch counts for the entire site or
 * for a specific category. The top 20 most watched items, if any, are returned
 * unless maxResults is used to specify a smaller result set. The top 20 items
 * are determined by the watch count totals from the preceding day. Ranking of
 * the most watched items is calculated with the latest watch count information.
 * <br><br>
 * Only active items are returned. Auction items are returned only when they 
 * have one or more bids. 
 * <p class="tablenote"><b>Note:</b> The <b class="con">
 * getMostWatchedItems</b> call does not work properly for EBAY-FRCA (eBay 
 * Canada, French). Refer to the 
 * <a href="http://dev-forums.ebay.com/thread.jspa?threadID=500006471">
 * getMostWatchedItems returns no results for IN, CAFR, CA</a> thread in
 * the eBay Shopping and Merchandising API Production System Announcements board
 * for more information, including an ETA for when this problem will be
 * resolved.</p>
 * 
 */
@Root(name = "getMostWatchedItemsRequest")
@Namespace(namespaceURI="http://www.ebay.com/marketplace/services", prefix="")
public class GetMostWatchedItemsRequest extends BaseMerchandisingServiceRequest  {


	@Element(name="categoryId")
	private String categoryId;
	
    
	/**
     * 
     * Specifies the category from which to retrieve item listings. This
     * field takes the same category ID data as used with other eBay APIs.
     * <br><br>
     * Category IDs are site-specific. If the specified category ID doesn't
     * match an existing category for the site, an invalid-category error
     * message is returned. To determine valid categories, you can use
     * either the Shopping API or the Trading API. In the Shopping API, use
     * the <a
     * href="http://developer.ebay.com/DevZone/shopping/docs/CallRef/FindItemsAdvanced.html">
     * FindItemsAdvanced</a> call with the CategoryHistogram value in
     * the IncludeSelector field to retrieve matching category information.
     * In the Trading API, use calls like <a
     * href="http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetCategories.html">
     * GetCategories</a> and <a 
     * href="http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetCategoryFeatures.html">
     * GetCategoryFeatures</a> to determine valid values for the site. 
     * 
	 */
	public String getCategoryId() {
	    return this.categoryId;
	}
	
	public void setCategoryId(String categoryId) {
	    this.categoryId = categoryId;
	}
	
}