// Generated by eBay Common SDK Platform
package com.ebay.services.merchandising;

import com.ebay.jxb.annotation.*;
/**
 * 
 * This is a response for operations that return item recommendations. Results consist
 * of an itemRecommendations array containing one or more item containers.
 * 
 */
@Root(name = "getMostWatchedItemsResponse")
@Namespace(namespaceURI="http://www.ebay.com/marketplace/services", prefix="")
public class MerchandisingServiceItemResponse extends BaseMerchandisingServiceResponse  {


	@Element(name="itemRecommendations")
	private ItemRecommendations itemRecommendations;
	
    
	/**
     * 
     * A list of items matching the given criteria. Item sort order is different
     * for each call. Returned when there are items that match the search
     * criteria.
     * 
	 */
	public ItemRecommendations getItemRecommendations() {
	    return this.itemRecommendations;
	}
	
	public void setItemRecommendations(ItemRecommendations itemRecommendations) {
	    this.itemRecommendations = itemRecommendations;
	}
	
}